FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev \
    && npm install -g json-server   # ← ADICIONADO
COPY . .
RUN apk add --no-cache curl
EXPOSE 3000
CMD ["json-server", "--watch", "mock-api/db.json", "--port", "3000", "--host", "0.0.0.0"]

HEALTHCHECK --interval=10s --timeout=3s --retries=3 \
  CMD curl -fs http://localhost:3000/contatos || exit 1

